---
version: '3'
services:
  db:
    image: mongo:5.0.14
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
    restart:
      unless-stopped
  app:
    container_name: app
    depends_on:
      - db
    build:
      context: .
    environment:
      - NEXT_DB_URL=mongodb://root:root@db:27017/bookshelf?authSource=admin
    ports:
      - "3000:3000/tcp"
    volumes:
      - ./public:/app/public
    restart:
      unless-stopped
